#!/bin/bash


chmod a+r *.cgi
chmod og-w *.cgi

cp -p createTeam.cgi ../.
cp -p createTeam.py ../.

cp -p createEvent.cgi ../.
cp -p createEvent.py ../.

cp -p createAccount.cgi ../.
cp -p createAccount.py ../.

cp -p addMember.cgi ../.
cp -p addMember.py ../.

cp -p dbconn.py ../.
cp -p rugsbee_dsn.py ../.

cp -p viewEvents.cgi ../.
cp -p viewEvents.py ../.

cp -p viewTeams.cgi ../.
cp -p viewTeams.py ../.

cp -p viewRoster.cgi ../.
cp -p viewRoster.py ../.


cp -p update-presence ../.

