#!/bin/bash


chmod a+rx *.cgi
chmod og-w *.cgi

cp createTeam.cgi ../.
cp createTeam.py ../.
cp createTeam.html ../.

cp createEvent.cgi ../.
cp createEvent.py ../.
cp createEvent.html ../.

cp createAccount.cgi ../.
cp createAccount.py ../.
cp createAccount.html ../.

cp addMember.cgi ../.
cp addMember.py ../.
cp addMember.html ../.

cp dbconn.py ../.
cp rugsbee_dsn.py ../.

cp viewEvents.cgi ../.
cp viewEvents.py ../.
cp viewEvents.html ../.

cp viewTeams.cgi ../.
cp viewTeams.py ../.
cp viewTeams.html ../.

cp viewRoster.cgi ../.
cp viewRoster.py ../.
cp viewRoster.html ../.

cp userDashboard.cgi ../.
cp userDash.html ../.

cp managerDashboard.cgi ../.
cp managerDash.html ../.

cp navbar.html ../.

cp index.html ../.

cp -p update-presence ../.

