#!/bin/bash

cp -p createTeam.cgi presence/.
cp -p createTeam.py presence/.

cp -p createEvent.cgi presence/.
cp -p createEvent.py presence/.

cp -p createAccount.cgi presence/.
cp -p createAccount.py presence/.

cp -p addMember.cgi presence/.
cp -p addMember.py presence/.

cp -p viewEvents.cgi presence/.
cp -p viewEvents.py presence/.

cp -p viewTeams.cgi presence/.
cp -p viewTeams.py presence/.

cp -p viewRoster.cgi presence/.
cp -p viewRoster.py presence/.




